version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orcasiq
      MYSQL_USER: orcasiq
      MYSQL_PASSWORD: orcasiq
    ports:
      - "3307:3306"  # host:container
    volumes:
      - mysql_data:/var/lib/mysql

  orcasiq-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orcasiq-app
    depends_on:
      - mysql-db
    ports:
      - "8001:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/orcasiq?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: orcasiq
      SPRING_DATASOURCE_PASSWORD: orcasiq
    restart: always

volumes:
  mysql_data:
